"""Binary classification surrogate models."""

from robotorchan.models.classification.binary.expressive import BinarySingleTaskDeepGPClassifier
from robotorchan.models.classification.binary.high_dimensional import (
    ALEBOBinarySingleTaskGPClassifier,
    JointEncoderBinaryGPClassifier,
    MapSaasBinarySingleTaskGPClassifier,
    PCABinarySingleTaskGPClassifier,
    PLSBinarySingleTaskGPClassifier,
    RandomProjectionBinarySingleTaskGPClassifier,
    ReducedBinarySingleTaskGPClassifier,
    SaasBinarySingleTaskGPClassifier,
)
from robotorchan.models.classification.binary.non_gp import (
    ExtraTreesBinaryClassifier,
    GradientBoostingBinaryClassifier,
    HistGradientBoostingBinaryClassifier,
    NonGPBinaryClassificationMixin,
    RandomForestBinaryClassifier,
    SklearnBinaryClassifier,
)
from robotorchan.models.classification.binary.robust import (
    ClassificationRobustnessType,
    ContaminatedBernoulliLikelihood,
    ContaminatedBinarySingleTaskGPClassifier,
    InputDependentLabelNoiseBinarySingleTaskGPClassifier,
    InputDependentLabelNoiseLikelihood,
    LabelNoiseBernoulliLikelihood,
    LabelNoiseBinarySingleTaskGPClassifier,
    MixedNonstationaryBinarySingleTaskGPClassifier,
    NonstationaryBinarySingleTaskGPClassifier,
    NonstationaryMultiTaskBinaryGPClassifier,
    ReplicateLabelBinarySingleTaskGPClassifier,
    RobustBinaryClassificationMixin,
    RobustClassificationMetadata,
)
from robotorchan.models.classification.binary.standard import (
    BinarySingleTaskGPClassifier,
    KroneckerMultiTaskBinaryGPClassifier,
    MixedBinarySingleTaskGPClassifier,
    MultiTaskBinaryGPClassifier,
)
from robotorchan.models.classification.binary.uncertain import (
    ClassificationInputUncertaintyType,
    ClassificationUncertaintyIntegration,
    ClassificationUncertaintyTarget,
    ContinuousUncertainInputBinarySingleTaskGPClassifier,
    UncertainBinaryClassificationMixin,
    UncertainCategoricalBinarySingleTaskGPClassifier,
    UncertainClassificationMetadata,
)

__all__ = [
    "ALEBOBinarySingleTaskGPClassifier",
    "BinarySingleTaskDeepGPClassifier",
    "BinarySingleTaskGPClassifier",
    "ClassificationInputUncertaintyType",
    "ClassificationRobustnessType",
    "ClassificationUncertaintyIntegration",
    "ClassificationUncertaintyTarget",
    "ContaminatedBernoulliLikelihood",
    "ContaminatedBinarySingleTaskGPClassifier",
    "ContinuousUncertainInputBinarySingleTaskGPClassifier",
    "ExtraTreesBinaryClassifier",
    "GradientBoostingBinaryClassifier",
    "HistGradientBoostingBinaryClassifier",
    "InputDependentLabelNoiseBinarySingleTaskGPClassifier",
    "InputDependentLabelNoiseLikelihood",
    "JointEncoderBinaryGPClassifier",
    "KroneckerMultiTaskBinaryGPClassifier",
    "LabelNoiseBernoulliLikelihood",
    "LabelNoiseBinarySingleTaskGPClassifier",
    "MapSaasBinarySingleTaskGPClassifier",
    "MixedBinarySingleTaskGPClassifier",
    "MixedNonstationaryBinarySingleTaskGPClassifier",
    "MultiTaskBinaryGPClassifier",
    "NonGPBinaryClassificationMixin",
    "NonstationaryBinarySingleTaskGPClassifier",
    "NonstationaryMultiTaskBinaryGPClassifier",
    "PCABinarySingleTaskGPClassifier",
    "PLSBinarySingleTaskGPClassifier",
    "RandomForestBinaryClassifier",
    "RandomProjectionBinarySingleTaskGPClassifier",
    "ReducedBinarySingleTaskGPClassifier",
    "ReplicateLabelBinarySingleTaskGPClassifier",
    "RobustBinaryClassificationMixin",
    "RobustClassificationMetadata",
    "SaasBinarySingleTaskGPClassifier",
    "SklearnBinaryClassifier",
    "UncertainBinaryClassificationMixin",
    "UncertainCategoricalBinarySingleTaskGPClassifier",
    "UncertainClassificationMetadata",
]
