import importlib  # noqa: I001


MODELS = importlib.import_module("robotorchan.models")

PUBLIC_MODEL_NAMES = {
    "ALEBOGP",
    "AdditiveMapSaasSingleTaskGP",
    "AutoEncoderGP",
    "AutoEncoderKroneckerMultiTaskGP",
    "AutoEncoderMultiTaskGP",
    "ContaminatedMultiTaskGP",
    "ContaminatedSingleTaskGP",
    "EnsembleMapSaasSingleTaskGP",
    "ExtraTreesSurrogate",
    "GradientBoostingSurrogate",
    "HistGradientBoostingSurrogate",
    "HeterogeneousMTGP",
    "HeteroskedasticMultiFidelityGP",
    "HeteroskedasticMultiTaskGP",
    "HeteroskedasticSingleTaskGP",
    "HierarchicalConditionalKernelGP",
    "HierarchicalConditionalKernelMultiTaskGP",
    "HigherOrderGP",
    "HybridAutoEncoderGP",
    "HybridAutoEncoderKroneckerMultiTaskGP",
    "HybridAutoEncoderMultiTaskGP",
    "InfiniteWidthBNNGP",
    "InfiniteWidthBNNMultiTaskGP",
    "MixedInfiniteWidthBNNGP",
    "MixedInfiniteWidthBNNMultiTaskGP",
    "JointHeteroskedasticSingleTaskGP",
    "JointEncoderGP",
    "JointEncoderKroneckerMultiTaskGP",
    "JointEncoderMultiTaskGP",
    "MixedJointEncoderMultiTaskGP",
    "JointVAEGP",
    "JointVAEKroneckerMultiTaskGP",
    "JointVAEMultiTaskGP",
    "KroneckerMultiTaskGP",
    "LCEAGP",
    "LCEMGP",
    "LatentKroneckerGP",
    "MixedAdditiveMapSaasSingleTaskGP",
    "MixedAutoEncoderGP",
    "MixedContaminatedMultiTaskGP",
    "MixedContaminatedSingleTaskGP",
    "MixedEnsembleMapSaasSingleTaskGP",
    "MixedHybridAutoEncoderGP",
    "MixedOrthogonalAdditiveGP",
    "MixedLatentKroneckerGP",
    "MixedLCEMGP",
    "MixedHigherOrderGP",
    "MixedHierarchicalConditionalKernelMultiTaskGP",
    "MixedHierarchicalConditionalKernelGP",
    "MixedHeterogeneousMTGP",
    "MixedHeteroskedasticMultiTaskGP",
    "MixedHeteroskedasticSingleTaskGP",
    "MixedJointEncoderGP",
    "MixedJointHeteroskedasticSingleTaskGP",
    "MixedJointVAEGP",
    "MixedKroneckerMultiTaskGP",
    "MixedMultiTaskDeepGP",
    "MixedMultiTaskGP",
    "MixedNonstationaryMultiTaskGP",
    "MixedNonstationarySingleTaskGP",
    "MixedPCAGP",
    "MixedPLSGP",
    "MixedRandomProjectionGP",
    "MixedReplicateNoiseSingleTaskGP",
    "MixedRobustRelevancePursuitMultiTaskGP",
    "MixedRobustRelevancePursuitSingleTaskGP",
    "MixedSaasFullyBayesianMultiTaskGP",
    "MixedSaasFullyBayesianSingleTaskGP",
    "MixedReducedGP",
    "MixedReducedKroneckerMultiTaskGP",
    "MixedReducedMultiTaskGP",
    "MixedSupervisedAutoEncoderGP",
    "MixedSupervisedVAEGP",
    "MixedUncertainInputSingleTaskGP",
    "MixedSingleTaskDeepGP",
    "MixedSingleTaskGP",
    "MixedStudentTMultiTaskGP",
    "MixedStudentTSingleTaskGP",
    "MixedSingleTaskMultiFidelityGP",
    "MixedSingleTaskVariationalGP",
    "MixedVAEGP",
    "ModelListGP",
    "MultiTaskDeepGP",
    "MultiTaskGP",
    "NonstationaryKroneckerMultiTaskGP",
    "NonstationaryMultiTaskGP",
    "NonstationarySingleTaskGP",
    "OrthogonalAdditiveGP",
    "OutputPCAGP",
    "OutputPLSGP",
    "PCAGP",
    "PCAMultiFidelityGP",\n    "PLSMultiFidelityGP",
    "PCAKroneckerMultiTaskGP",
    "PCAMultiTaskGP",
    "PLSGP",
    "PLSKroneckerMultiTaskGP",
    "PLSMultiTaskGP",
    "PairwiseGP",
    "NGBoostSurrogate",
    "RandomForestSurrogate",
    "RandomProjectionGP",
    "RandomProjectionKroneckerMultiTaskGP",
    "RandomProjectionMultiTaskGP",
    "ReducedGP",
    "ReducedKroneckerMultiTaskGP",
    "ReducedMultiTaskGP",
    "ReplicateNoiseMultiFidelityGP",
    "ReplicateNoiseSingleTaskGP",
    "RobustRelevancePursuitMultiTaskGP",
    "RobustRelevancePursuitSingleTaskGP",
    "SACGP",
    "SaasFullyBayesianMultiTaskGP",
    "SaasFullyBayesianSingleTaskGP",
    "SingleTaskDeepGP",
    "SingleTaskGP",
    "SpectralMixtureGP",
    "SpectralMixtureMultiTaskGP",
    "MixedSpectralMixtureGP",
    "MixedSpectralMixtureMultiTaskGP",
    "SingleTaskMultiFidelityGP",
    "SingleTaskVariationalGP",
    "SupervisedAutoEncoderGP",
    "SupervisedAutoEncoderKroneckerMultiTaskGP",
    "SupervisedAutoEncoderMultiTaskGP",
    "SupervisedVAEGP",
    "SupervisedVAEKroneckerMultiTaskGP",
    "SupervisedVAEMultiTaskGP",
    "StudentTMultiTaskGP",
    "StudentTSingleTaskGP",
    "UncertainCategoricalSingleTaskGP",
    "UncertainInputSingleTaskGP",
    "VAEGP",
    "VAEKroneckerMultiTaskGP",
    "VAEMultiTaskGP",
}

NON_MLL_MODELS = {
    "StudentTMultiTaskGP",
    "MixedStudentTMultiTaskGP",
    "MixedContaminatedMultiTaskGP",
    "ContaminatedMultiTaskGP",
    "ContaminatedSingleTaskGP",
    "MixedContaminatedSingleTaskGP",
    "JointHeteroskedasticSingleTaskGP",
    "MixedJointHeteroskedasticSingleTaskGP",
    "MixedStudentTSingleTaskGP",
    "StudentTSingleTaskGP",
    "MixedSaasFullyBayesianMultiTaskGP",
    "MixedSaasFullyBayesianSingleTaskGP",
    "SaasFullyBayesianMultiTaskGP",
    "SaasFullyBayesianSingleTaskGP",
    "RandomForestSurrogate",
    "ExtraTreesSurrogate",
    "GradientBoostingSurrogate",
    "HistGradientBoostingSurrogate",
    "NGBoostSurrogate",
}


def test_public_model_exports_are_complete_and_explicit() -> None:
    exported = set(MODELS.__all__)

    assert exported == PUBLIC_MODEL_NAMES | {"UnsupportedModelOperationError"}


def test_public_model_names_resolve_to_matching_classes() -> None:
    for name in PUBLIC_MODEL_NAMES:
        model_class = getattr(MODELS, name)

        assert isinstance(model_class, type)
        assert model_class.__name__ == name


def test_all_public_models_expose_training_capability_contract() -> None:
    for name in PUBLIC_MODEL_NAMES:
        model_class = getattr(MODELS, name)

        assert hasattr(model_class, "supports_mll")
        assert hasattr(model_class, "make_mll")
        assert model_class.supports_mll is (name not in NON_MLL_MODELS)
