"""Classification surrogate-model contracts."""

from robotorchan.models.classification.base import (
    ClassificationLikelihoodFamily,
    ClassificationMetadata,
    ClassificationModelMixin,
    LatentOutputStructure,
)
from robotorchan.models.classification.binary import (
    ALEBOBinarySingleTaskGPClassifier,
    BinarySingleTaskDeepGPClassifier,
    BinarySingleTaskGPClassifier,
    ClassificationInputUncertaintyType,
    ClassificationRobustnessType,
    ClassificationUncertaintyIntegration,
    ClassificationUncertaintyTarget,
    ContaminatedBernoulliLikelihood,
    ContinuousUncertainInputBinarySingleTaskGPClassifier,
    ContaminatedBinarySingleTaskGPClassifier,
    InputDependentLabelNoiseBinarySingleTaskGPClassifier,
    InputDependentLabelNoiseLikelihood,
    JointEncoderBinaryGPClassifier,
    KroneckerMultiTaskBinaryGPClassifier,
    LabelNoiseBernoulliLikelihood,
    LabelNoiseBinarySingleTaskGPClassifier,
    MapSaasBinarySingleTaskGPClassifier,
    MixedBinarySingleTaskGPClassifier,
    MixedNonstationaryBinarySingleTaskGPClassifier,
    MultiTaskBinaryGPClassifier,
    NonstationaryBinarySingleTaskGPClassifier,
    NonstationaryMultiTaskBinaryGPClassifier,
    PCABinarySingleTaskGPClassifier,
    PLSBinarySingleTaskGPClassifier,
    RandomProjectionBinarySingleTaskGPClassifier,
    ReducedBinarySingleTaskGPClassifier,
    ReplicateLabelBinarySingleTaskGPClassifier,
    RobustBinaryClassificationMixin,
    RobustClassificationMetadata,
    SaasBinarySingleTaskGPClassifier,
    UncertainBinaryClassificationMixin,
    UncertainClassificationMetadata,
)
from robotorchan.models.classification.binary.base import BinaryClassificationMixin
from robotorchan.models.classification.binary.validation import validate_binary_labels
from robotorchan.models.classification.model_list import ClassificationModelList
from robotorchan.models.classification.registry import (
    CLASSIFICATION_MODEL_REGISTRY,
    ClassificationModelRegistryEntry,
    get_classification_model_class,
    get_classification_model_entry,
    list_classification_models,
)

__all__ = [
    "CLASSIFICATION_MODEL_REGISTRY",
    "ALEBOBinarySingleTaskGPClassifier",
    "BinaryClassificationMixin",
    "BinarySingleTaskDeepGPClassifier",
    "BinarySingleTaskGPClassifier",
    "ClassificationInputUncertaintyType",
    "ClassificationLikelihoodFamily",
    "ClassificationMetadata",
    "ClassificationModelList",
    "ClassificationModelMixin",
    "ClassificationModelRegistryEntry",
    "ClassificationRobustnessType",
    "ClassificationUncertaintyIntegration",
    "ClassificationUncertaintyTarget",
    "ContaminatedBernoulliLikelihood",
    "ContaminatedBinarySingleTaskGPClassifier",
    "ContinuousUncertainInputBinarySingleTaskGPClassifier",
    "InputDependentLabelNoiseBinarySingleTaskGPClassifier",
    "InputDependentLabelNoiseLikelihood",
    "JointEncoderBinaryGPClassifier",
    "KroneckerMultiTaskBinaryGPClassifier",
    "LabelNoiseBernoulliLikelihood",
    "LabelNoiseBinarySingleTaskGPClassifier",
    "LatentOutputStructure",
    "MapSaasBinarySingleTaskGPClassifier",
    "MixedBinarySingleTaskGPClassifier",
    "MixedNonstationaryBinarySingleTaskGPClassifier",
    "MultiTaskBinaryGPClassifier",
    "NonstationaryBinarySingleTaskGPClassifier",
    "NonstationaryMultiTaskBinaryGPClassifier",
    "PCABinarySingleTaskGPClassifier",
    "PLSBinarySingleTaskGPClassifier",
    "RandomProjectionBinarySingleTaskGPClassifier",
    "ReducedBinarySingleTaskGPClassifier",
    "ReplicateLabelBinarySingleTaskGPClassifier",
    "RobustBinaryClassificationMixin",
    "RobustClassificationMetadata",
    "SaasBinarySingleTaskGPClassifier",
    "UncertainBinaryClassificationMixin",
    "UncertainClassificationMetadata",
    "get_classification_model_class",
    "get_classification_model_entry",
    "list_classification_models",
    "validate_binary_labels",
]
